name: 🚀 Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📁 Checkout Repository
        uses: actions/checkout@v7

      - name: 🚀 Deploy to Cloudflare Pages
        id: deploy-to-cloudflare-pages
        uses: cloudflare/wrangler-action@v4
        with:
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./src --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }} --commit-dirty=true
